name: Run automatic labeling

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

on:
  push:
    branches:
      - develop
  pull_request_target:
    types:
      - opened
      - synchronize
      - edited

permissions: {}

jobs:
  run-labels-script:
    name: Run script
    runs-on: ubuntu-slim
    if: github.repository_owner == 'PrismLauncher'

    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{ vars.PULL_REQUEST_APP_ID }}
          private-key: ${{ secrets.PULL_REQUEST_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          sparse-checkout: '.github/scripts'

      - name: Run labeling script
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          github-token: ${{ steps.generate-token.outputs.token || github.token }}
          retries: 3
          script: |
            const script = require('.github/scripts/labels.js')
            await script({github, context})