name: Build Application and Make Release

on:
  push:
    tags:
      - "*"

permissions: {}

jobs:
  build_release:
    name: Build Release
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      # Required for Azure Trusted Signing
      id-token: write
      # Required for vcpkg binary cache
      packages: write
    with:
      environment: Release
    secrets: inherit

  create_release:
    needs: build_release
    permissions:
      contents: write
    runs-on: ubuntu-slim
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: "true"
          path: "PrismLauncher-source"
      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      - name: Grab and store version
        run: |
          tag_name=$(echo ${{ github.ref }} | grep -oE "[^/]+$")
          echo "VERSION=$tag_name" >> $GITHUB_ENV
      - name: Package artifacts properly
        run: |
          mv ${{ github.workspace }}/PrismLauncher-source PrismLauncher-${{ env.VERSION }}
          mv PrismLauncher-Linux-Qt6-Portable*/PrismLauncher-portable.tar.gz PrismLauncher-Linux-Qt6-Portable-${{ env.VERSION }}.tar.gz
          mv PrismLauncher-*.AppImage/PrismLauncher-*-x86_64.AppImage PrismLauncher-Linux-x86_64.AppImage
          mv PrismLauncher-macOS*/PrismLauncher.zip PrismLauncher-macOS-${{ env.VERSION }}.zip
          mv PrismLauncher-macOS*/PrismLauncher.dmg PrismLauncher-macOS-${{ env.VERSION }}.dmg

          tar --exclude='.git' -czf PrismLauncher-${{ env.VERSION }}.tar.gz PrismLauncher-${{ env.VERSION }}

          for d in PrismLauncher-Windows-MSVC*; do
            cd "${d}" || continue
            LEGACY="$(echo -n ${d} | grep -o Legacy || true)"
            INST="$(echo -n ${d} | grep -o Setup || true)"
            PORT="$(echo -n ${d} | grep -o Portable || true)"
            NAME="PrismLauncher-Windows-MSVC"
            test -z "${LEGACY}" || NAME="${NAME}-Legacy"
            test -z "${PORT}" || NAME="${NAME}-Portable"
            test -z "${INST}" || mv PrismLauncher-*.exe ../${NAME}-Setup-${{ env.VERSION }}.exe
            test -n "${INST}" || zip -r -9 "../${NAME}-${{ env.VERSION }}.zip" *
            cd ..
          done

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          name: Prism Launcher ${{ env.VERSION }}
          draft: true
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            PrismLauncher-Linux-x86_64.AppImage
            PrismLauncher-Linux-Qt6-Portable-${{ env.VERSION }}.tar.gz
            PrismLauncher-Windows-MSVC-${{ env.VERSION }}.zip
            PrismLauncher-Windows-MSVC-Portable-${{ env.VERSION }}.zip
            PrismLauncher-Windows-MSVC-Setup-${{ env.VERSION }}.exe
            PrismLauncher-macOS-${{ env.VERSION }}.zip
            PrismLauncher-macOS-${{ env.VERSION }}.dmg
            PrismLauncher-${{ env.VERSION }}.tar.gz
